@namespace
class SpriteKind:
    wizard = SpriteKind.create()
    slime_boss = SpriteKind.create()
    firedragon = SpriteKind.create()

def on_a_pressed():
    the_player.set_image(img("""
        ...................
                ...................
                ...................
                ......fffff......f.
                .....f77777f....f7f
                ....f7777777ffff77f
                ....f7777777777777f
                ....f7777777777fff.
                .....ffffffffff....
                .....f55555555f....
                .....f55f55f55f....
                .....f55555555f....
                .....f5f555555f....
                .....f55ffff55f....
                .....f55555555f....
                .....ffffffffff....
                ..ffff77777777ffff.
                .f7777777ff7777777f
                .f777777777777ff77f
                .f77ff777ff755ff77f
                .f77ff777777557777f
                .f77ff777ff755ffff.
                .fff..fffffbbbb....
                f222ffeeeffe66f....
                f2f2ffeeeffe66f....
                f222ffeeeffe66f....
                .f2f.feeeffeeef....
                ..f.ffeeeffeeeff...
                ...feeeeeffeeeeef..
                ..feeeeeeffeeeeeef.
    """))
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_overlap_tile(sprite, location):
    global firedragon_agro
    fire_dragon.follow(the_player, 50)
    firedragon_agro = True
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        myTile7
    """),
    on_overlap_tile)

def on_on_overlap(sprite, otherSprite):
    game.splash("hello I am the old man")
    game.splash("you must escape")
    game.splash("I,m in here 100 years")
    pause(5000)
sprites.on_overlap(SpriteKind.player, SpriteKind.wizard, on_on_overlap)

def on_on_overlap2(sprite, otherSprite):
    global slime_boss_health
    if controller.A.is_pressed():
        slime_boss_health += -1
        pause(500)
sprites.on_overlap(SpriteKind.player, SpriteKind.slime_boss, on_on_overlap2)

def on_on_overlap3(sprite, otherSprite):
    if firedragon_agro == True:
        pause(5000)
        info.change_life_by(-1)
sprites.on_overlap(SpriteKind.player, SpriteKind.firedragon, on_on_overlap3)

def on_on_overlap4(sprite, otherSprite):
    if controller.A.is_pressed():
        otherSprite.set_image(img("""
            2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                        2 2 f 2 f 2 f 2 2 f 2 2 2 2 2 2 
                        2 2 f f f 2 2 2 f f f 2 2 2 2 2 
                        2 2 f 2 f 2 f 2 2 f 2 2 2 2 2 2 
                        2 2 f 2 f 2 f 2 2 f 2 2 2 2 2 2 
                        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                        2 2 2 2 4 2 2 2 2 2 2 2 2 2 2 2 
                        2 2 2 4 5 4 2 2 2 2 2 2 2 2 2 2 
                        2 2 4 5 5 5 4 2 2 2 2 2 4 2 2 2 
                        2 2 2 4 5 4 2 2 2 2 2 4 5 4 2 2 
                        2 2 2 2 4 2 2 2 2 2 4 5 5 5 4 2 
                        2 2 2 2 2 2 2 2 2 2 2 4 5 4 2 2 
                        2 2 2 2 2 2 2 2 2 2 2 2 4 2 2 2 
                        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
                        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
        """))
        pause(500)
        otherSprite.destroy()
    info.change_life_by(-1)
    pause(2000)
sprites.on_overlap(SpriteKind.player, SpriteKind.enemy, on_on_overlap4)

projectile: Sprite = None
slimeball: Sprite = None
firedragon_agro = False
fire_dragon: Sprite = None
the_player: Sprite = None
game.splash("aaaaaah... where am I.")
game.splash("whats this?")
game.splash("a note you find says this: \"you, you will never escape this dungeon mwa ha ha\"")
game.splash("whats on my arm?")
game.splash("a strange symbol it seems.")
game.splash("why am I here any way")
info.set_score(10)
fireball = sprites.create(img("""
        . . . . . . . . . . . . . . . . 
            . . . . . 4 4 4 4 4 4 4 . . . . 
            . . . . 4 4 4 4 4 4 4 4 4 . . . 
            . . . 4 4 5 5 5 5 5 5 5 4 4 . . 
            . . 4 4 5 5 5 5 5 5 5 5 5 4 4 . 
            . . 4 4 5 5 5 5 5 5 5 5 5 4 4 . 
            . . 4 4 5 5 f 5 5 5 f 5 5 4 4 . 
            . . 4 4 5 5 f 5 5 5 f 5 5 4 4 . 
            . . 4 4 5 5 f 5 5 5 f 5 5 4 4 . 
            . . 4 4 5 5 5 5 5 5 5 5 5 4 4 . 
            . . 4 4 5 5 5 5 5 5 5 5 5 4 4 . 
            . . . 4 4 5 5 5 5 5 5 5 4 4 . . 
            . . . . 4 4 4 4 4 4 4 4 4 . . . 
            . . . . . 4 4 4 4 4 4 4 . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . .
    """),
    SpriteKind.enemy)
fire_ball3 = sprites.create(img("""
        . . . . . . . . . . . . . . . . 
            . . . . . 4 4 4 4 4 4 4 . . . . 
            . . . . 4 4 4 4 4 4 4 4 4 . . . 
            . . . 4 4 5 5 5 5 5 5 5 4 4 . . 
            . . 4 4 5 5 5 5 5 5 5 5 5 4 4 . 
            . . 4 4 5 5 5 5 5 5 5 5 5 4 4 . 
            . . 4 4 5 5 f 5 5 5 f 5 5 4 4 . 
            . . 4 4 5 5 f 5 5 5 f 5 5 4 4 . 
            . . 4 4 5 5 f 5 5 5 f 5 5 4 4 . 
            . . 4 4 5 5 5 5 5 5 5 5 5 4 4 . 
            . . 4 4 5 5 5 5 5 5 5 5 5 4 4 . 
            . . . 4 4 5 5 5 5 5 5 5 4 4 . . 
            . . . . 4 4 4 4 4 4 4 4 4 . . . 
            . . . . . 4 4 4 4 4 4 4 . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . .
    """),
    SpriteKind.enemy)
fireball2 = sprites.create(img("""
        . . . . . . . . . . . . . . . . 
            . . . . . 4 4 4 4 4 4 4 . . . . 
            . . . . 4 4 4 4 4 4 4 4 4 . . . 
            . . . 4 4 5 5 5 5 5 5 5 4 4 . . 
            . . 4 4 5 5 5 5 5 5 5 5 5 4 4 . 
            . . 4 4 5 5 5 5 5 5 5 5 5 4 4 . 
            . . 4 4 5 5 f 5 5 5 f 5 5 4 4 . 
            . . 4 4 5 5 f 5 5 5 f 5 5 4 4 . 
            . . 4 4 5 5 f 5 5 5 f 5 5 4 4 . 
            . . 4 4 5 5 5 5 5 5 5 5 5 4 4 . 
            . . 4 4 5 5 5 5 5 5 5 5 5 4 4 . 
            . . . 4 4 5 5 5 5 5 5 5 4 4 . . 
            . . . . 4 4 4 4 4 4 4 4 4 . . . 
            . . . . . 4 4 4 4 4 4 4 . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . .
    """),
    SpriteKind.enemy)
spawn_ball = sprites.create(img("""
        .................................
            .............ffffffff............
            ...........fff6bbbb6fff..........
            .........ff6bbb6666bbb6ff........
            .......ff6bb6666ff6666bb6f.......
            ......f6bbb66ffffffff666bbf......
            .....f6bb1bb66fffffffff66bbf.....
            ....f6bb111bb66ffffffffff6bbf....
            ....fbbb111b66ffffffffffff6bbf...
            ...f6bb111b66ffffffffffffff6bf...
            ...fbb611b66fffffffffffffff66bf..
            ..f6b6b11b66ffffffffffffffff6bf..
            ..fbb6b1b66fffffffffffffffff6bff.
            ..fb6fb1b6fffffffffffffffffff66f.
            ..fb6f6b6ffffffffffffffffffff66f.
            ..fb6ff6fffffffffffffffffffff6bf.
            ..fb6ffffffffffffffffffffffff6bf.
            ..fb6ffffffffffffffffffffffff6bf.
            ..fb6ffffffffffffffffffffffff6bf.
            ..f66ffffffffffffffffffffffff66f.
            ..f66ffffffffffffffffffffffff66f.
            ..ffb6ffffffffffffffffffffff6bff.
            ...fb6ffffffffffffffffffffff6bf..
            ...fb66ffffffffffffffffffff66bf..
            ....fb6ffffffffffffffffffff6bf...
            ....fbb6ffffffffffffffffff6bbf...
            .....fbb6ffffffffffffffff6bbf....
            ......fbb66ffffffffffff66bbf.....
            .......fbb666ffffffff666bbf......
            ........f6bb6666ff6666bb6f.......
            .........ff6bbb6666bbb6ff........
            ...........fff6bbbb6fff..........
    """),
    SpriteKind.player)
tiles.set_tilemap(tilemap("""
    dungeon1
"""))
tiles.place_on_random_tile(fireball, assets.tile("""
    myTile2
"""))
tiles.place_on_random_tile(fire_ball3, assets.tile("""
    myTile2
"""))
tiles.place_on_random_tile(fireball2, assets.tile("""
    myTile2
"""))
slime_boss2 = sprites.create(assets.image("""
    slime boss
"""), SpriteKind.slime_boss)
the_player = sprites.create(img("""
        .................ff
            ................f7f
            .......ffff...ff77f
            ......f7777fff7777f
            ......f7777777777f.
            .....f77777777777f.
            .....f777777777ff..
            .....ffffffffff....
            .....f55555555f....
            .....f55f55f55f....
            .....f55555555f....
            .....f5f555555f....
            .....f55ffff55f....
            .....f55555555f....
            ......ffffffff.....
            .....f77777777f....
            ..ffff777ff777fff..
            .f777777777777777f.
            .f7777777ff7777777f
            .f77ff77777777ff77f
            .fffff777ff777ff77f
            f2222f77777777ff77f
            f2ff2ffffffffff.ee.
            f2222feeeffeeef.ee.
            .f22ffeeeffeeefbbbb
            ..ff.feeeffeeef.66.
            .....feeeffeeef.66.
            ....feeeeffeeeef66.
            ...feeeeeffeeeeef..
            ...ffffffffffffff..
    """),
    SpriteKind.player)
enemy1 = sprites.create(img("""
        ....................
            ....................
            ....................
            ....................
            ....................
            ........77..........
            .......7777.........
            ......777777........
            ......717717........
            ......7f77f7........
            ......7f77f7........
            ......777777........
            ......777777........
            ......77..77........
            .....777..777.......
            ....777....777......
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
    """),
    SpriteKind.enemy)
slime_boss_health = 5
fire_dragon = sprites.create(img("""
        ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ....................fffff.........................
            ...................f77777.........................
            ...................f77777.........................
            ...................f77777..ffffff.................
            ...................f77777.f777777.................
            ...................f77777.f777777.................
            ...................f77777.f777777.................
            ...................f77777.f777777.................
            ...................f77777.f777777.................
            ...................f77777.f777777.................
            ...................f77777.f777777.................
            ...................f77777.f777777.................
            ...................ffffffffffff77.................
            .............ffffff777777777777ff.................
            ..........fff77f77777777777777777ffff.............
            .......ffffb777f77777777777777777777ff............
            .....ff777c1777f777777777777777777777f............
            ....f7777777777f7777777777777777fff77f............
            .....fffff77777f77777777ffffffff..f77f............
            ..........fffffffffffffff7f.f7f...f7ff............
            ..................f7ff7ff7f.f7f...f7f.............
            ..................f7ff7ff7f.f7f...f7f.............
            ..................f7ff7ff7f.f7f....f..............
            ..................f7ff7ff7f.f7f...................
            ..................f7ff7ff7f.f7f...................
            ..................f7f.f..f...f....................
            ..................f7f.............................
            ..................f7f.............................
            ..................f7f.............................
            ...................f..............................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
    """),
    SpriteKind.firedragon)
tiles.place_on_random_tile(fire_dragon, tiles.util.object6)
slime_boss2.follow(the_player)
tiles.place_on_random_tile(enemy1, assets.tile("""
    tile
"""))
tiles.place_on_random_tile(slime_boss2, tiles.util.object4)
enemy1.follow(the_player)
controller.move_sprite(the_player)
scene.camera_follow_sprite(the_player)
scene.set_background_color(11)
info.set_life(5)
old_man = sprites.create(img("""
        . 8 8 8 8 8 8 8 8 8 8 . . . . . 
            8 8 . 8 8 8 8 8 8 8 8 8 . . . . 
            8 . . . . d d d d d d 8 . . . . 
            . . . . d d d d d d d d . . . . 
            . . . . d d f d d f d d . . . . 
            . . . . d d d d d d d d . . . . 
            . . . . d f d d d d f d . . . . 
            . d d . b d f f f f d b d d . . 
            . d d . b b d d d d b b d d . . 
            . 8 8 b 8 b b b b b b 8 8 8 . . 
            . 8 b b 8 8 b b b b b 8 8 8 . . 
            . 8 b b b b b b b b 8 8 8 8 . . 
            . 8 8 8 b b b b b b 8 8 8 8 . . 
            . . . 8 8 8 8 8 8 8 8 8 . . . . 
            . . . 8 8 . . . . . 8 8 . . . . 
            . . . f f f f . . . f f f f . .
    """),
    0)
tiles.place_on_random_tile(old_man, tiles.util.object1)
old_man.set_kind(SpriteKind.wizard)
firedragonhealth = 5
firedragon_agro = False

def on_update_interval():
    global slimeball
    slimeball = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . 7 7 7 7 7 7 7 . . . . 
                    . . . . 7 6 6 6 7 7 7 7 7 . . . 
                    . . . 7 7 6 6 6 7 7 7 7 7 7 . . 
                    . . 7 7 7 6 6 6 7 7 7 7 7 7 7 . 
                    . . 7 7 7 7 7 7 7 6 6 6 7 7 7 . 
                    . . 7 7 7 7 7 7 7 6 6 6 7 7 7 . 
                    . . 7 7 7 7 7 7 7 6 6 6 7 7 7 . 
                    . . 7 7 7 7 7 7 7 7 7 7 7 7 7 . 
                    . . 7 7 7 7 7 7 7 7 7 7 7 7 7 . 
                    . . 7 7 7 7 7 7 7 7 7 7 7 7 7 . 
                    . . . 7 7 7 7 7 7 7 7 7 7 7 . . 
                    . . . . 7 7 7 7 7 7 7 7 7 . . . 
                    . . . . . 7 7 7 7 7 7 7 . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        slime_boss2,
        0,
        50)
    slimeball = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . 7 7 7 7 7 7 7 . . . . 
                    . . . . 7 6 6 6 7 7 7 7 7 . . . 
                    . . . 7 7 6 6 6 7 7 7 7 7 7 . . 
                    . . 7 7 7 6 6 6 7 7 7 7 7 7 7 . 
                    . . 7 7 7 7 7 7 7 6 6 6 7 7 7 . 
                    . . 7 7 7 7 7 7 7 6 6 6 7 7 7 . 
                    . . 7 7 7 7 7 7 7 6 6 6 7 7 7 . 
                    . . 7 7 7 7 7 7 7 7 7 7 7 7 7 . 
                    . . 7 7 7 7 7 7 7 7 7 7 7 7 7 . 
                    . . 7 7 7 7 7 7 7 7 7 7 7 7 7 . 
                    . . . 7 7 7 7 7 7 7 7 7 7 7 . . 
                    . . . . 7 7 7 7 7 7 7 7 7 . . . 
                    . . . . . 7 7 7 7 7 7 7 . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        slime_boss2,
        0,
        -50)
    slimeball = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . 7 7 7 7 7 7 7 . . . . 
                    . . . . 7 6 6 6 7 7 7 7 7 . . . 
                    . . . 7 7 6 6 6 7 7 7 7 7 7 . . 
                    . . 7 7 7 6 6 6 7 7 7 7 7 7 7 . 
                    . . 7 7 7 7 7 7 7 6 6 6 7 7 7 . 
                    . . 7 7 7 7 7 7 7 6 6 6 7 7 7 . 
                    . . 7 7 7 7 7 7 7 6 6 6 7 7 7 . 
                    . . 7 7 7 7 7 7 7 7 7 7 7 7 7 . 
                    . . 7 7 7 7 7 7 7 7 7 7 7 7 7 . 
                    . . 7 7 7 7 7 7 7 7 7 7 7 7 7 . 
                    . . . 7 7 7 7 7 7 7 7 7 7 7 . . 
                    . . . . 7 7 7 7 7 7 7 7 7 . . . 
                    . . . . . 7 7 7 7 7 7 7 . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        slime_boss2,
        50,
        0)
game.on_update_interval(2000, on_update_interval)

def on_forever():
    global projectile
    if controller.B.is_pressed() and info.life() < 5:
        projectile = sprites.create_projectile_from_sprite(img("""
                ........................
                            ........................
                            ........................
                            ........................
                            ..........ffff..........
                            ........ff1111ff........
                            .......fb111111bf.......
                            .......f11111111f.......
                            ......fd11111111df......
                            ......fd11111111df......
                            ......fddd1111dddf......
                            ......fbdbfddfbdbf......
                            ......fcdcf11fcdcf......
                            .......fb111111bf.......
                            ......fffcdb1bdffff.....
                            ....fc111cbfbfc111cf....
                            ....f1b1b1ffff1b1b1f....
                            ....fbfbffffffbfbfbf....
                            .........ffffff.........
                            ...........fff..........
                            ........................
                            ........................
                            ........................
                            ........................
            """),
            the_player,
            0,
            50)
        projectile = sprites.create_projectile_from_sprite(img("""
                ........................
                            ........................
                            ........................
                            ........................
                            ..........ffff..........
                            ........ff1111ff........
                            .......fb111111bf.......
                            .......f11111111f.......
                            ......fd11111111df......
                            ......fd11111111df......
                            ......fddd1111dddf......
                            ......fbdbfddfbdbf......
                            ......fcdcf11fcdcf......
                            .......fb111111bf.......
                            ......fffcdb1bdffff.....
                            ....fc111cbfbfc111cf....
                            ....f1b1b1ffff1b1b1f....
                            ....fbfbffffffbfbfbf....
                            .........ffffff.........
                            ...........fff..........
                            ........................
                            ........................
                            ........................
                            ........................
            """),
            the_player,
            0,
            -50)
        projectile = sprites.create_projectile_from_sprite(img("""
                ........................
                            ........................
                            ........................
                            ........................
                            ..........ffff..........
                            ........ff1111ff........
                            .......fb111111bf.......
                            .......f11111111f.......
                            ......fd11111111df......
                            ......fd11111111df......
                            ......fddd1111dddf......
                            ......fbdbfddfbdbf......
                            ......fcdcf11fcdcf......
                            .......fb111111bf.......
                            ......fffcdb1bdffff.....
                            ....fc111cbfbfc111cf....
                            ....f1b1b1ffff1b1b1f....
                            ....fbfbffffffbfbfbf....
                            .........ffffff.........
                            ...........fff..........
                            ........................
                            ........................
                            ........................
                            ........................
            """),
            the_player,
            50,
            0)
        projectile = sprites.create_projectile_from_sprite(img("""
                ........................
                            ........................
                            ........................
                            ........................
                            ..........ffff..........
                            ........ff1111ff........
                            .......fb111111bf.......
                            .......f11111111f.......
                            ......fd11111111df......
                            ......fd11111111df......
                            ......fddd1111dddf......
                            ......fbdbfddfbdbf......
                            ......fcdcf11fcdcf......
                            .......fb111111bf.......
                            ......fffcdb1bdffff.....
                            ....fc111cbfbfc111cf....
                            ....f1b1b1ffff1b1b1f....
                            ....fbfbffffffbfbfbf....
                            .........ffffff.........
                            ...........fff..........
                            ........................
                            ........................
                            ........................
                            ........................
            """),
            the_player,
            -50,
            0)
        pause(1000)
forever(on_forever)

def on_forever2():
    if slime_boss_health == 1:
        fireball.follow(the_player)
        fire_ball3.follow(the_player)
        fireball2.follow(the_player)
forever(on_forever2)

def on_forever3():
    if firedragon_agro == True:
        fire_dragon.set_image(img("""
            ..................................................
                        ..................................................
                        ..................................................
                        ..................................................
                        ..................................................
                        ..................................................
                        ..................................................
                        ..................................................
                        ..................................................
                        ....................fffff.........................
                        ...................f77777.........................
                        ...................f77777.........................
                        ...................f77777..ffffff.................
                        ...................f77777.f777777.................
                        ...................f77777.f777777.................
                        ...................f77777.f777777.................
                        ...................f77777.f777777.................
                        ...................f77777.f777777.................
                        ...................f77777.f777777.................
                        ...................f77777.f777777.................
                        ...................f77777.f777777.................
                        ...................ffffffffffff77.................
                        .............ffffff777777777777ff.................
                        .44.......fff77f77777777777777777ffff.............
                        4544...ffffb777f77777777777777777777ff............
                        45544ff777c1777f777777777777777777777f............
                        455544777777777f7777777777777777fff77f............
                        45544fffff77777f77777777ffffffff..f77f............
                        4544......fffffffffffffff7f.f7f...f7ff............
                        44................f7ff7ff7f.f7f...f7f.............
                        ..................f7ff7ff7f.f7f...f7f.............
                        ..................f7ff7ff7f.f7f....f..............
                        ..................f7ff7ff7f.f7f...................
                        ..................f7ff7ff7f.f7f...................
                        ..................f7f.f..f...f....................
                        ..................f7f.............................
                        ..................f7f.............................
                        ..................f7f.............................
                        ...................f..............................
                        ..................................................
                        ..................................................
                        ..................................................
                        ..................................................
                        ..................................................
                        ..................................................
                        ..................................................
                        ..................................................
                        ..................................................
                        ..................................................
                        ..................................................
        """))
forever(on_forever3)

def on_forever4():
    print(firedragonhealth)
forever(on_forever4)

def on_forever5():
    global firedragonhealth
    if the_player.overlaps_with(fire_dragon):
        if controller.A.is_pressed():
            firedragonhealth += -1
            pause(1000)
forever(on_forever5)

def on_forever6():
    if firedragonhealth == 0:
        tiles.place_on_random_tile(the_player, sprites.dungeon.collectible_insignia)
forever(on_forever6)

def on_forever7():
    global firedragonhealth
    if firedragonhealth == 0:
        fire_dragon.destroy()
        info.set_life(6)
        firedragonhealth = 1
forever(on_forever7)

def on_forever8():
    global slime_boss_health
    if slime_boss_health == 0:
        slime_boss2.destroy()
        info.set_life(7)
        slime_boss_health = 1
forever(on_forever8)

def on_forever9():
    eternal_doom = 0
    if eternal_doom == 666:
        game.splash("end")
        game.over(False)
forever(on_forever9)

def on_forever10():
    if slime_boss_health == 1:
        sprites.create_projectile_from_sprite(img("""
                . . . . . . . . . . . . . . . . 
                            . . . . . 7 7 7 7 7 7 7 . . . . 
                            . . . . 7 6 6 6 7 7 7 7 7 . . . 
                            . . . 7 7 6 6 6 7 7 7 7 7 7 . . 
                            . . 7 7 7 6 6 6 7 7 7 7 7 7 7 . 
                            . . 7 7 7 7 7 7 7 6 6 6 7 7 7 . 
                            . . 7 7 7 7 7 7 7 6 6 6 7 7 7 . 
                            . . 7 7 7 7 7 7 7 6 6 6 7 7 7 . 
                            . . 7 7 7 7 7 7 7 7 7 7 7 7 7 . 
                            . . 7 7 7 7 7 7 7 7 7 7 7 7 7 . 
                            . . 7 7 7 7 7 7 7 7 7 7 7 7 7 . 
                            . . . 7 7 7 7 7 7 7 7 7 7 7 . . 
                            . . . . 7 7 7 7 7 7 7 7 7 . . . 
                            . . . . . 7 7 7 7 7 7 7 . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . .
            """),
            slime_boss2,
            -50,
            0).destroy()
forever(on_forever10)

def on_forever11():
    if the_player.overlaps_with(slimeball):
        info.change_life_by(-1)
        pause(5000)
forever(on_forever11)

def on_forever12():
    music.play_melody("C D E F G F E F ", 111)
    music.play_melody("E D D C D E E F ", 111)
    music.play_melody("E D C D E D E F ", 111)
    music.play_melody("D E F E D E F E ", 111)
forever(on_forever12)

def on_forever13():
    if controller.left.is_pressed() or controller.right.is_pressed() or (controller.up.is_pressed() or controller.down.is_pressed()):
        the_player.set_image(img("""
            .................ff
                        ................f7f
                        .......ffff...ff77f
                        ......f7777fff7777f
                        ......f7777777777f.
                        .....f77777777777f.
                        .....f777777777ff..
                        .....ffffffffff....
                        .....f55555555f....
                        .....f55f55f55f....
                        .....f55555555f....
                        .....f5f555555f....
                        .....f55ffff55f....
                        .....f55555555f....
                        ......ffffffff.....
                        .....f77777777f....
                        ..ffff777ff777fff..
                        .f777777777777777f.
                        .f7777777ff7777777f
                        .f77ff77777777ff77f
                        .fffff777ff777ff77f
                        f2222f77777777ff77f
                        f2ff2ffffffffff.ee.
                        f2222feeeffeeef.ee.
                        .f22ffeeeffeeefbbbb
                        ..ff.feeeffeeef.66.
                        .....feeeffeeef.66.
                        ....feeeeffeeeef66.
                        ...feeeeeffeeeeef..
                        ...ffffffffffffff..
        """))
        pause(100)
        the_player.set_image(img("""
            ...................
                        ...................
                        ...................
                        ......fffff......f.
                        .....f77777f....f7f
                        ....f7777777ffff77f
                        ....f7777777777777f
                        ....f7777777777fff.
                        .....ffffffffff....
                        .....f55555555f....
                        .....f55f55f55f....
                        .....f55555555f....
                        .....f5f555555f....
                        .....f55ffff55f....
                        .....f55555555f....
                        .....ffffffffff....
                        ..ffff77777777ffff.
                        .f7777777ff7777777f
                        .f7777777777777777f
                        .f77ff777ff777ff77f
                        .f77ff77777777ff77f
                        .f77ff777ff777f.ee.
                        .fff..fffffffff.ee.
                        f222ffeeeffeeefbbbb
                        f2f2ffeeeffeeef.66.
                        f222ffeeeffeeef.66.
                        .f2f.feeeffeeef.66.
                        ..f.ffeeeffeeeff...
                        ...feeeeeffeeeeef..
                        ..feeeeeeffeeeeeef.
        """))
        pause(100)
forever(on_forever13)
